### ISSUE TITLE
Only AMQP protocol working for SendEventAsync

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#115]
I have a classic .net 4.6.1 app that I'm attempting to use with the mqtt transport as its my understanding that is the only transport that supports device direct methods (and possibly device twins). Removing any complexities of that scenario, the most simple test is to simply connect and then send a message:

`			await deviceClient.SendEventAsync(Message).ConfigureAwait(false);`

 If I specify the amqp protocol, that works fine. If I specify http1, I get a NullReferenceException from something internal to DeviceClient. If I specify MQTT, I get a timeout exception.

mqtt TimeoutException stacktrace:

> at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Azure.IoT.Gateway.Modules.IoTHubRelay.<SendMessageAsync>d__21.MoveNext() in C:\Wield\IoTHub\Wield.Gateway\IoTHubRelay.Shared\IoTHubRelay.cs:line 55
> 
> 

http NullReferenceException stacktrace: 

>     at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass17_0.<SendEventAsync>b__0()
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass19_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__20`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__20`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<TryExecuteActionAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendMessageWithRetryAsync>d__25.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendEventAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<SendEventAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Azure.IoT.Gateway.Modules.IoTHubRelay.<SendMessageAsync>d__21.MoveNext() in C:\Wield\IoTHub\Wield.Gateway\IoTHubRelay.Shared\IoTHubRelay.cs:line 55

**Comment by v-tbert** [comment]
I should add my nuget package versions:

`<packages>
  <package id="DotNetty.Buffers" version="0.4.5" targetFramework="net461" />
  <package id="DotNetty.Codecs" version="0.4.5" targetFramework="net461" />
  <package id="DotNetty.Codecs.Mqtt" version="0.4.5" targetFramework="net461" />
  <package id="DotNetty.Common" version="0.4.5" targetFramework="net461" />
  <package id="DotNetty.Handlers" version="0.4.5" targetFramework="net461" />
  <package id="DotNetty.Transport" version="0.4.5" targetFramework="net461" />
  <package id="EnterpriseLibrary.TransientFaultHandling" version="6.0.1304.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.Azure.Amqp" version="2.0.6" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Client" version="1.2.11" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Gateway.Native.Windows.x64" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Azure.Devices.Shared" version="1.0.11" targetFramework="net461" />
  <package id="Microsoft.Azure.IoT.Gateway.Module" version="1.0.3" targetFramework="net461" />
  <package id="Microsoft.Azure.KeyVault.Core" version="2.0.4" targetFramework="net461" />
  <package id="Microsoft.Data.Edm" version="5.8.2" targetFramework="net461" />
  <package id="Microsoft.Data.OData" version="5.8.2" targetFramework="net461" />
  <package id="Microsoft.Data.Services.Client" version="5.8.2" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.1.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="net461" />
  <package id="PInvoke.BCrypt" version="0.5.64" targetFramework="net461" />
  <package id="PInvoke.Kernel32" version="0.5.64" targetFramework="net461" />
  <package id="PInvoke.NCrypt" version="0.5.64" targetFramework="net461" />
  <package id="PInvoke.Windows.Core" version="0.5.64" targetFramework="net461" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net461" />
  <package id="System.ComponentModel.EventBasedAsync" version="4.3.0" targetFramework="net461" />
  <package id="System.Console" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.1" targetFramework="net461" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net461" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net461" />
  <package id="System.IO" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Queryable" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.2" targetFramework="net461" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Requests" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net461" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
  <package id="System.Spatial" version="5.8.2" targetFramework="net461" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />
  <package id="Validation" version="2.4.15" targetFramework="net461" />
  <package id="WindowsAzure.Storage" version="8.1.3" targetFramework="net461" />
</packages>`

**Comment by v-tbert** [comment]
I have determined that the problem with MQTT is a deadlock of some sort. I was getting a timeout exception as reported above so I stopped setting OperationTimeoutInMilliseconds and then the program would never get past SendEventAsync. I then created an empty message object and it sent successfully. What I eventually determined was that setting any one of a few of the Message fields to null or empty string would cause a deadlock when you call SendEventAsync. For example:

`					var temp = new Microsoft.Azure.Devices.Client.Message(UTF8Encoding.Default.GetBytes("fubar"));
					temp.To = "fake";  //null or string.Empty will cause SendEventAsync to deadlock
					temp.CorrelationId = "fake";   //null or string.Empty will cause SendEventAsync to deadlock
					temp.MessageId = "fake";  //null or string.Empty will cause SendEventAsync to deadlock
					temp.UserId = null;     //null ok
					deviceClient.SendEventAsync(temp).Wait(); 
					deviceClient.SendEventAsync(temp).Wait(); //this call will fail with NullReferenceException, also a bug
`

**Comment by tameraw** [comment]
@v-tbert - A lot in the code has changed since this issue was initially reported. Please try with the latest and if still seeing problems please reopen the issue. Thanks.

**Comment by Navlesh** [comment]
Issue still exist with Http protocol, it's works fine with AMQP protocol.
I am using .Net Core 2.0, Microsoft.Azure.Devices.Client 1.7.1 using certificate based authentication.

**Comment by prmathur-microsoft** [comment]
Can you try with 1.20.0? We believe we have handled issues like this over there.

**Comment by CIPop** [comment]
This should be fixed in 1.19+ - likely caused by `ApplyTimeout`.

**Comment by az-iot-builder-01** [comment]
@v-tbert, @Navlesh, @prmathur-microsoft, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by dgodwin1175** [comment]
I am still experiencing this issue with version 1.25.0.

AMQP over websockets working fine, but have recently changed the TransportType to Http1 in the following code:
`_deviceClient = DeviceClient.CreateFromConnectionString(GetConnectionString(), _transportType);`

But when calling SendEventAsync:
`await _deviceClient.SendEventAsync(message);`

It will always throw this exception:

2021-02-18 11:30:04.701 [6] ERROR FluentLogger::LogError(26)	testy:System.Func`1[System.String]. ex: System.NullReferenceException: **Object reference not set to an instance of an object**.
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass16_0.<SendEventAsync>b__0()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()

**Comment by bikamani** [comment]
@dgodwin1175 

With Http1 this should not be a problem, to verify I also tested a sample with Http1 as a protocol and version 1.25.0 for device client package. 

You can use this sample snippet for a reference: https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/DeviceReconnectionSample#send-device-to-cloud-telemetry

Also, while it's not required it would be recommended to use the latest version. We've had many new changes and fixes since last year, I'd like to know if you have an option to upgrade to the latest SDK.

Let us know if this helps. If not, please provide logs using this guideline: 
![image](https://user-images.githubusercontent.com/41314966/108416219-3ffd1e80-71e3-11eb-9fb8-6ce605ad8f4a.png)

**Comment by dgodwin1175** [comment]
Thanks @bikamani for the response.  
I found the issue was in my message, I was inserting a null into the CorrelationId, and for some reason this was causing the exception when the TransportType was Http.

So instead of doing this:
`message.CorrelationId = header.CorrelationId;`

I'm now doing this:
`if (header.CorrelationId != null)
    message.CorrelationId = header.CorrelationId;`

**Comment by dgodwin1175** [comment]
@bikamani, quick question on DeviceClient support for AMQP-WSS (websockets secure).  Is this, or can this be supported?  
If not through the DeviceClient, is there another supported mechanism in the SDK?
Thanks.

[AMQP-WS(S) spec](http://docs.oasis-open.org/amqp-bindmap/amqp-wsb/v1.0/amqp-wsb-v1.0.html)

**Comment by bikamani** [comment]
@dgodwin1175 

We support AMQP Web Socket and you can see list of supported features for device client per protocol here: https://github.com/Azure/azure-iot-sdk-csharp#iot-hub-device-sdk

I am not aware of any support for AMQP-WS(S) however I'd love to know if that's a requirement for your product/project.

**Comment by dgodwin1175** [comment]
@bikamani, we do have customers that don't like opening up port 80 which is required for AMQP-WS (before the connection is upgraded to 443).  We can switch them to HTTPS but would prefer to use AMQP-WSS.  Is it worth putting in a request for this feature and if so, how do I do that?

**Comment by abhipsaMisra** [comment]
All communication between our clients and IoT Hub happen over a secured channel (TLS encrypted), so if you use the Amqp_Ws transport channel as recommended by @bikamani, it should communicate over a secured channel using port 443.

**Comment by dgodwin1175** [comment]
Hi Abhipsa,

Yes, but AMQP-WS protocol must first open a connection over HTTP before the connection is upgrade to HTTPS, as per the AMQP-WS spec<http://docs.oasis-open.org/amqp-bindmap/amqp-wsb/v1.0/cs01/amqp-wsb-v1.0-cs01.html#_Toc461801609>.
As mentioned, a number of our customers have a problem with opening up port 80 from the secure networks in order to send their data to the cloud, for now we are falling back to a transport type of HTTP for those customers, but support for AMQP-WSS would be the ideal solution.

Would you consider adding this as an enhancement?

Thanks.

**Comment by bikamani** [comment]
@dgodwin1175 On our repository issue tab when you click on "New issue" there is an option to select "feature request", add all details there for your requirements.

Do mention the priority and impact with adding this enhancement so it can be evaluated correctly.

**Comment by abhipsaMisra** [comment]
@dgodwin1175 If you don't mind, I'd like to get some more details about your particular scenario.

While it is true that websocket connection requests are made via HTTP/HTTPS connection upgrade requests, a secure websocket connection can be established by requesting for an upgrade over an HTTPS connection (443) directly.
This is also what I see if I inspect the websocket connections made via our clients:

```
Websocket tunnel to my-iot-hub.azure-devices.net:443

GET https://my-iot-hub.azure-devices.net/$iothub/websocket HTTP/1.1
Host: my-iot-hub.azure-devices.net
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: ++dBvgrk6wtCkKZhfaQ==
Sec-WebSocket-Protocol: AMQPWSB10


HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Server: Microsoft-HTTPAPI/2.0
Sec-WebSocket-Protocol: AMQPWSB10
Connection: Upgrade
Sec-WebSocket-Accept: 9/Keq9dYfZPs8Fgaqelw2ZAY=
Date: Tue, 23 Feb 2021 01:53:28 GMT
EndTime: 17:53:36.688
ReceivedBytes: 1325
SentBytes: 1944
```

Additionally, inspecting the traffic with a filter for port 80 yields 0 traces.

If you inspect the ws traffic at your end, do you see connections being established over port 80?

**Comment by dgodwin1175** [comment]
Hi Abhipsa,

Thanks for that information.  Can you confirm which tool you used to inspect the websocket connections?

**Comment by abhipsaMisra** [comment]
I used Wireshark and Fiddler for inspecting the traffic.
