### ISSUE TITLE
Timeout InvokeDeviceMethodAsync leads to DeviceNotFoundException instead of TimeoutException

### ISSUE THREAD

**Issue by v-tbert** [Azure/azure-iot-sdk-csharp#122]
I left a ServiceClient running overnight and tried to use the connection to invoke a device method in the morning. Presumably it was no longer connected because it sat for a long time and then eventually returned an aggregate exception. The inner exception was a Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException but from the message it clearly timed out. The device definitely exists so it is misleading that it doesn't lead to a TimeoutException.	

> {"Device {\"Message\":\"{\\\"errorCode\\\":404103,\\\"trackingId\\\":\\\"92db2a129fd941338e0ecdd2a7e00e60-G:3-TimeStamp:06/16/2017 14:12:27\\\",\\\"message\\\":\\\"Timed out waiting for device to connect.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:01:00\\\"},\\\"timestampUtc\\\":\\\"2017-06-16T14:12:27.9626139Z\\\"}\",\"ExceptionMessage\":\"\"} not registered"}	System.Exception {}

**Comment by tameraw** [comment]
@v-tbert - Thanks for filing this. I agree that it's misleading. Should be fixed.
If interested in providing us with a PR, we'd happily review it.

**Comment by sergaz-msft** [comment]
Hi @v-tbert can you still reproduce this issue easily and let me know the steps for doing it? Also what was the version of the sdk that you were using when the issue occurred? Thanks!

**Comment by ChangeTheCode** [comment]
Hi @sergaz-msft I obtain the same exception. I try to run this code: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-node-direct-methods 

This Device definitely exists at the IoT hub.

**Comment by sergaz-msft** [comment]
Hello @ChangeTheCode , I am not sure how to reproduce this issue. You are calling a method from a device that is disconnected but registered on IoTHub? This means: "ConnectionState:Disconnected" and "State:Enabled" ?

Also please confirm that you can reproduce the issue using the latest version of C# SDK: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2017-6-30

Thanks :)!

**Comment by sergaz-msft** [comment]
Hello @ChangeTheCode I am closing this issue since we didn't hear back from you for a while. Please reopen it if you are still facing the issue. Thanks!

**Comment by rizwaans** [comment]
Hi, please check if you can help with the below situation
I'm trying to invoke a method on the device module without having to provide any timeout number. my current code is as below
var methodInvocation = new CloudToDeviceMethod("invokesenddicomimages") { ResponseTimeout = TimeSpan.FromSeconds(300) };
can someone help me achieving this code. I know if don't specify the timeout it will be defaulted to 30 seconds but I just want to invoke the method and don't bother about the response.

**Comment by CIPop** [comment]
@rizwaans In general we're not monitoring closed issues. 

Please open a new issue and filling in information required from the new issue template.

**Comment by rizwaans** [comment]
@CIPop  I opened a new issue, #6625 can you please help me to get a fix for this issue :) many thanks
