### ISSUE TITLE
Getting Operation timeout expired exception frequently while sending telemetry data

### ISSUE THREAD

**Issue by mathisharp** [Azure/azure-iot-sdk-csharp#301]
Hi SupportTeam, 

We are using DeviceClient of Azure IOT hub to send data to device.

- **OS used:** <VERSION> Windows 10

- **Protocol used:** <VERSION> Amqp_WebSocket_Only

- **SDK version used:** <VERSION> IoT Device Client 1.5.0

- **programming language used:** <VERSION> C#

- **IOThub Units:** <VERSION>  20 units

- **Quota/Standard:** <VERSION>  S1

- **DeviceConnected:** <VERSION> 75

- **Device running parallel:** <VERSION>  - 5 to 10

# Description of the issue:

	Sudden operation timeout exception while sending telemetry to IOThub. We have multiple device simulator running in a machine. With each device sending telemetry data to different iothubs.
	We noticed that only one of the device simulator gets this exception, but other devices sending data to the same iothub didn't face any issue.

# Code sample exhibiting the issue:

 
	
Note. : 
	We are facing this issue from last month.
	
We have also rolled out the following possibility- 
	
	1) Devices being disabled.
	2) firewall block.
        3) Exceeding quota limit.

		
We had checked there is no firewall block or device disabled or quota exceed during the test run. Please let us know any updates on fixing this issue.

# Console log of the issue:

ERROR -- Failed to send message: MessageType MessageV1 MessageId 6ff8856e-dac1-4add-b6bb-d9ab040bfb7a, Exception-System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by CIPop** [comment]
/cc @yzhong94 

Thanks for reporting this @mathisharp. When you say "sudden" you mean that the retry policy (default or custom) that you are using is not respected?

 > We are facing this issue from last month.

Did you upgrade the SDK version before this started? Otherwise this could be something on the server side, in which case you will need to use the Azure Portal to report the issue through customer support. Please __do not__ share any hub information here.
/cc @mastermanu 

TimeoutException is expected from the client if any network or server side issue occurred. The default retry policy will re-attempt this using an exponential back-off policy for the next 4 minutes.

Please add more details regarding the type of traffic: 
- Could you please share the information on how you've reached the conclusion this was not done by the quota? (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling)
- How many requests/second does each device have? 
- Are there other network services running on the same server? 
- Do you have network information such as number of connections, ephemeral ports in use, throughput, etc when the timeout occurs?

**Comment by sergaz-msft** [comment]
@CIPop This issue is also being tracked by CSS. Customer opened a ticket through Azure Portal. I will add you to the email thread.

**Comment by mathisharp** [comment]
@CIPop 
• Could you please share the information on how you've reached the conclusion this was not done by the quota? (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling)
The total number of active devices were less than 10 and each device was sending 11 requests per second. All messages were of size ~16KB. Also we are not seeing any throttling errors reported on the IotHub metrics graph in the azure portal. Hence we concluded that the throttling limit was not reached
•	How many requests/second does each device have?
    11 requests/ second
•	Are there other network services running on the same server?
The VM running the device sdk has basic windows services and Antivirus services running. What other network services are you interested in?
•	Do you have network information such as number of connections, ephemeral ports in use, throughput, etc when the timeout occurs?
How do we calculate this? Could you please help us generate this information?

**Comment by mathisharp** [comment]
[Issue.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1581974/Issue.zip)
Hi @CIPop, 
We are able to reproduce the issue as said earlier below are the details.

Case:
•	We have only device in the IOT hub.
•	IOT hub units is set to 10.
•	Sending 10 messages per second of size 16 kB.
•	Once the application is started after 5 to 10 minutes getting operation timeout expired exception.

Environment:

•	OS used: Windows 10
•	Protocol used: Amqp_WebSocket_Only
•	SDK version used: IoT Device Client 1.6.0
•	programming language used: C#
•	IOThub Units: 10 units
•	Quota/Standard: S1
•	DeviceConnected: 1
•	Device running parallel: - 1
Our understanding – 

For S1 Tier – 1111 KB/minute per unit.
Our IOT hub Unit is set to 10 
So Total capacity is 10 X 1111 KB = 11110 KB per Minute.

Our example project is sending 160 KB per second X 60 = 9600 KB per minute, which is lesser than the total capacity.
Referred - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-scaling

PFA the sample project.

**Comment by tameraw** [comment]
Issue resolved.

**Comment by traghunathan** [comment]
@tameraw  Do this issue handled in the latest release 1.6.1?

**Comment by sergaz-msft** [comment]
Hello @traghunathan , that's correct. We fixed a leak and a few issues with the retry policy implementation.

**Comment by traghunathan** [comment]
Thanks @sergaz-msft.
I tested the application with retry policy as "NoRetry". But, we still received the below exception for some random devices. Do i have to change the retry policy from "NoRetry"?, if so please suggest.

Exception Message- 
![image](https://user-images.githubusercontent.com/3650020/35028190-b33417ba-fb7a-11e7-8b07-75babf5cc1af.png)

Need help!

**Comment by sergaz-msft** [comment]
Hello @traghunathan , you have three different retry policies: 

"Retry policy for unsuccessful device-to-cloud messages have three options: no try, exponential backoff with jitter (default) and custom."

[from here](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/RetryPolicyType.cs)

```csharp
{
    using System;

    /// <summary>
    /// Retry Strategy types supported by DeviceClient
    /// </summary>
    [Obsolete("This enum has been deprecated.  Please use Microsoft.Azure.Devices.Client.SetRetryPolicy(IRetryPolicy retryPolicy) instead.")]
    public enum RetryPolicyType
    {
        /// <summary>
        /// No retry.  A single attempt of operation.
        /// </summary>
        No_Retry = 0,

        /// <summary>
        /// A retry strategy which exponentially augments the retry delay and adds a random value to the delay at each retry.
        /// This is the DEFAULT policy to use
        /// </summary>
        Exponential_Backoff_With_Jitter = 1,
    }
}
```

Can you detail better the sdk version you are using and if the device is not able to reestablish the connection after the exception?

Thanks

**Comment by traghunathan** [comment]
Hello @sergaz-msft 
SDK Version : 1.6.1
	
In our code, we are using **NoRetry** Policy, Sample code is below 
![image](https://user-images.githubusercontent.com/3650020/35078694-6d3b72da-fc29-11e7-8755-816512870b2b.png)
	
Also, 
Once we receive the exception, we are closing the connection. 
When we try to reestablish the new connection for same device, we able to achieve it.

**Comment by sergaz-msft** [comment]
Hello @traghunathan can you detail better why don't you use the default retry policy (exponential backoff with jitter) for achieving the same result?
